import type { DataMode, Provenance } from '@/lib/types'

/**
 * Badges are the product's honesty surface. Every one of them pairs a colour
 * with a word, because colour alone would fail both accessibility and the rule
 * that a reader must never have to infer provenance.
 */

const TONE_CLASSES = {
  neutral: 'bg-ink-100 text-ink-700 ring-ink-200',
  brand: 'bg-brand-100 text-brand-700 ring-brand-500/30',
  ok: 'bg-ok-100 text-ok-700 ring-ok-700/20',
  warn: 'bg-flag-100 text-flag-700 ring-flag-700/25',
  heat: 'bg-heat-100 text-heat-700 ring-heat-600/25',
  stop: 'bg-stop-100 text-stop-700 ring-stop-700/25',
} as const

export type BadgeTone = keyof typeof TONE_CLASSES

export function Badge({
  children,
  tone = 'neutral',
  title,
  className = '',
}: {
  children: React.ReactNode
  tone?: BadgeTone
  title?: string
  className?: string
}) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide ring-1 ring-inset ${TONE_CLASSES[tone]} ${className}`}
      title={title}
    >
      {children}
    </span>
  )
}

const DATA_MODE_TONE: Record<DataMode, BadgeTone> = {
  LIVE_FORTYGUARD: 'ok',
  CACHED_REAL_DATA: 'brand',
  DEMO_SYNTHETIC: 'warn',
  BLOCKED_LIVE: 'stop',
}

const DATA_MODE_LABEL: Record<DataMode, string> = {
  LIVE_FORTYGUARD: 'Live FortyGuard',
  CACHED_REAL_DATA: 'Cached real data',
  DEMO_SYNTHETIC: 'Demo — synthetic',
  BLOCKED_LIVE: 'Blocked live',
}

export function DataModeBadge({ mode, className }: { mode: DataMode; className?: string }) {
  return (
    <Badge
      tone={DATA_MODE_TONE[mode]}
      className={className ?? ''}
      title={
        mode === 'DEMO_SYNTHETIC'
          ? 'Values on this screen were generated by the demo fixture, not measured.'
          : mode === 'LIVE_FORTYGUARD'
            ? 'Values came from a live FortyGuard heatmap request.'
            : mode === 'CACHED_REAL_DATA'
              ? 'Values came from a stored response to an earlier live FortyGuard request.'
              : 'The live FortyGuard path has not been executed.'
      }
    >
      {DATA_MODE_LABEL[mode]}
    </Badge>
  )
}

const PROVENANCE_TONE: Record<Provenance, BadgeTone> = {
  REAL: 'ok',
  DERIVED: 'brand',
  PROXY: 'warn',
  SYNTHETIC: 'warn',
  UNKNOWN: 'neutral',
}

export function ProvenanceBadge({ provenance }: { provenance: Provenance }) {
  return (
    <Badge
      tone={PROVENANCE_TONE[provenance]}
      title={
        provenance === 'REAL'
          ? 'Copied verbatim from an official published source.'
          : provenance === 'DERIVED'
            ? 'Computed by this project from official sources.'
            : provenance === 'SYNTHETIC'
              ? 'Generated by the demo fixture. Not a measurement.'
              : provenance === 'PROXY'
                ? 'A stand-in for a quantity this project cannot measure directly.'
                : 'No source establishes this value.'
      }
    >
      {provenance}
    </Badge>
  )
}

const GATE_TONE: Record<string, BadgeTone> = {
  PASS: 'ok',
  PASS_WITH_LIMITATIONS: 'brand',
  PASS_FIXTURE: 'brand',
  BLOCKED_LIVE: 'warn',
  NOT_AVAILABLE: 'neutral',
  FAIL: 'stop',
}

export function GateBadge({ status }: { status: string }) {
  return <Badge tone={GATE_TONE[status] ?? 'neutral'}>{status.replace(/_/g, ' ')}</Badge>
}

const CONFIDENCE_TONE: Record<string, BadgeTone> = {
  high: 'ok',
  medium: 'brand',
  low: 'warn',
  unknown: 'neutral',
}

export function ConfidenceBadge({ band, score }: { band: string; score: number }) {
  return (
    <Badge tone={CONFIDENCE_TONE[band] ?? 'neutral'} title={`Confidence score ${score} / 100`}>
      {band} {score.toFixed(0)}
    </Badge>
  )
}
